<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="register_users.php" method="post">
    <label for="">Имя</label>
    <input type="text" name="name"><br>
    <label for="">Фамилия</label>
    <input type="text" name="family"><br>
    <label for="">Возраст</label>
    <input type="number" name="age"><br>
    <input type="submit" value="REGISTER">
</form>

</body>
</html>
